[#829] Normalize codecept test names (connects #829
open-learning-exchange/BeLL-Apps pull request #1014
Opened 2017-08-31 08:48 UTC by razu9861

2017-08-31 10:29 UTC, dogi requested changes
please do not delete tests/feedback_tset.js

2017-09-04 05:11 UTC, lmmrssa reviewed
it seems there are lot of lines changed then commented out. So could we just remove those lines.

2017-09-05 06:03 UTC, razu9861 commented
@dogi feedback_test is in function

2017-09-07 11:20 UTC, dogi approved these changes

2017-09-11 03:54 UTC, nirojdyola approved these changes

2017-09-12 10:13 UTC, dogi approved these changes

2017-09-12 10:56 UTC, merged