[#1022] Mock data for course (connects #1022)
open-learning-exchange/BeLL-Apps pull request #1023
Opened 2017-09-07 06:35 UTC by Pr0chin

2017-09-07 06:44 UTC, Pr0chin commented
![d1](https://user-images.githubusercontent.com/24644003/30149635-1d76a360-93c8-11e7-811b-1c11134e8826.png)
![d2](https://user-images.githubusercontent.com/24644003/30149639-1ee12b58-93c8-11e7-8ff3-a3e8b079a98e.png)
![d3](https://user-images.githubusercontent.com/24644003/30149644-1ffed008-93c8-11e7-80ac-4c1d6d4e6841.png)
![d4](https://user-images.githubusercontent.com/24644003/30149647-217a3896-93c8-11e7-9b5f-780e2157caed.png)
![d5](https://user-images.githubusercontent.com/24644003/30149648-23170224-93c8-11e7-827a-823284fef330.png)
![d6](https://user-images.githubusercontent.com/24644003/30149650-247fc362-93c8-11e7-8b87-778afd969d8a.png)
![d7](https://user-images.githubusercontent.com/24644003/30149651-25962d9a-93c8-11e7-9ccf-294cb7944f7b.png)

![d8](https://user-images.githubusercontent.com/24644003/30149662-2dede302-93c8-11e7-9f2b-84126cf7df3d.png)

2017-09-07 06:56 UTC, Pr0chin commented on mock_data
> +var n_courses = 1 ; //Number of Iteration to run for courses
@dogi  as i have initialize variable var n_courses = 1 as a static value we can remove variable and loop statement for course if we need only one course.

2017-09-07 09:16 UTC, leomaxi commented
Looks okay, what about quiz ?. Does the scrip also create a simple quiz in the course ?

2017-09-07 10:14 UTC, nirojdyola submitted a review, later dismissed

2017-09-07 10:18 UTC, Pr0chin commented
@leonardmensah  yes :D it creates course having one steps and 4 different types of question i.e MCQ, single-text, attachment and comment-box. if u want to run this mock data then u should run 
**node [script_name] [url]**

2017-09-11 03:56 UTC, razu9861 submitted a review, later dismissed

2017-09-11 07:51 UTC, Rupesh87 submitted a review, later dismissed

2017-09-12 10:36 UTC, dogi requested changes
Generally we want 2 courses:
1 one step and in there all kind of questions
2 make a team meeting adiscuss about how the ultimative Course should look like to later on test stuff on with travis really fast ...

2017-09-12 10:36 UTC, dogi commented on tests/mock_data
> +// Increase Limits so couchapp push works correctly
not needed on linux please start only when MacOS detected

2017-09-12 10:36 UTC, dogi commented on tests/mock_data
> +var sys = require('sys')
please exchange `sys` with `util`

2017-09-15 06:41 UTC, Pr0chin commented
![aa](https://user-images.githubusercontent.com/24644003/30469629-e4a81d3a-9a10-11e7-8b52-ef3533f495c9.png)
![a](https://user-images.githubusercontent.com/24644003/30469634-e767b3fa-9a10-11e7-8127-5bbad0257e59.png)
![b](https://user-images.githubusercontent.com/24644003/30469637-e97988da-9a10-11e7-95bf-1d06ed6a9b0f.png)
![d](https://user-images.githubusercontent.com/24644003/30469673-1dfcbabe-9a11-11e7-9140-20d8ae416837.png)
![e](https://user-images.githubusercontent.com/24644003/30469675-209b254e-9a11-11e7-8bc4-aa15890f6227.png)
![ff](https://user-images.githubusercontent.com/24644003/30469680-23394a4c-9a11-11e7-878e-bfafe74ef3a0.png)
![g](https://user-images.githubusercontent.com/24644003/30469682-24d1809a-9a11-11e7-9bcd-c0fdb9da0543.png)

2017-09-15 06:44 UTC, Pr0chin commented
@dogi I have made mode_data as per your concern. please give me some feedback regarding to course mock_data.

2017-09-15 11:21 UTC, dogi commented
@Rupesh87 @razu9861 @nirojdyola please review again ;)

2017-09-18 04:06 UTC, nirojdyola commented on tests/course_mock_data
> +            for(var i = 0; i < 1; i++){
If it is only for two courses then it is fine, otherwise it should be change.

2017-09-18 10:32 UTC, dogi approved these changes

2017-09-18 10:34 UTC, merged