[#1008] Download attatchment answer button fixed in answer review (connects#1008)
open-learning-exchange/BeLL-Apps pull request #1030
Opened 2017-09-14 05:13 UTC by razu9861

![screen shot 2017-09-14 at 10 50 24 am](https://user-images.githubusercontent.com/24647983/30413043-951fdb0c-993b-11e7-892b-bf94f7bafc10.png)
![screen shot 2017-09-14 at 10 56 45 am](https://user-images.githubusercontent.com/24647983/30413048-979ac4fa-993b-11e7-9460-608bf839893d.png)

2017-09-14 05:20 UTC, nirojdyola commented on app/MyApp/app/views/AnswerReview.js
> +                //var attachmentName = [];
Do we need this ?

2017-09-14 05:25 UTC, razu9861 commented on app/MyApp/app/views/AnswerReview.js
> +                //var attachmentName = [];
removed

2017-09-15 10:23 UTC, dogi approved these changes
looks good so far

2017-09-21 04:54 UTC, Rupesh87 approved these changes

2017-10-02 05:02 UTC, lmmrssa requested changes

2017-10-02 05:02 UTC, lmmrssa commented on app/MyApp/app/views/listSyncDbView.js
> +
extra space

2017-10-02 05:02 UTC, lmmrssa commented on app/MyApp/index.html
> +                            <td>Assignment Name</td>
Add translation

2017-10-05 08:58 UTC, razu9861 commented
@dogi Tests failing at Language selection

2017-10-10 08:59 UTC, lmmrssa approved these changes

2017-10-11 04:16 UTC, closed without merging