[#630] vip link (connects #360)
open-learning-exchange/BeLL-Apps pull request #642
Opened 2017-03-06 04:36 UTC by razu9861

2017-03-06 10:37 UTC, Pr0chin approved these changes

2017-03-06 10:39 UTC, lmmrssa approved these changes
seems some extra changes but could not figure out what is causing it may be due to way OS treating space character differently

2017-03-06 10:39 UTC, Rupesh87 approved these changes

2017-03-06 10:41 UTC, nirojdyola approved these changes

2017-03-06 12:54 UTC, dogi requested changes
I approve all the files except `app/nation/app/Router.js`

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +            $.ajax({
hmm - @razu9861 there is no difference in the code why is github bringing it up?
is it because of whitespaces?

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +                    $('input.date-picker').datepicker('setDate', endDateForTrendReport);
some here ...

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +                var nationUrl = $.url().data.attr.authority;
and here

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +                $.ajax({
and here

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +                        if (urlFrag[2]) {
and here

2017-03-06 12:54 UTC, dogi commented on app/nation/app/Router.js
> +})
it kinda looks like that the only maybe valid fix here is the whitespaces one in line 3707 ...
or in other words theoretically there is no change at all

@razu9861 think we have to check your editors whitespace policy

2017-03-09 02:51 UTC, dogi commented
![85-1](https://cloud.githubusercontent.com/assets/13684059/23733873/4010c3d8-0449-11e7-8138-3cb4ce16e42f.png)

@dogi found out that we are really fix spaces (left new/fix | right old)

2017-03-09 02:52 UTC, dogi approved these changes

2017-03-14 07:08 UTC, closed without merging