[#638] Removed duplication of code (connects #638)
open-learning-exchange/BeLL-Apps pull request #644
Opened 2017-03-08 13:05 UTC by nirojdyola

2017-03-08 22:52 UTC, dogi commented
@nirojdyola this breaks the tests again ...

2017-03-09 02:15 UTC, dogi requested changes
@nirojdyola I opened in https://github.com/ole-vi/BeLL-Apps/issues/77 where we will check about the fail of the whole test ... lets hope soon we know more ;)

2017-03-09 04:15 UTC, razu9861 approved these changes

2017-03-14 10:10 UTC, dogi approved these changes

2017-03-17 06:56 UTC, Pr0chin approved these changes

2017-03-17 10:09 UTC, closed without merging