636 vip link logined lang(connects #636)
open-learning-exchange/BeLL-Apps pull request #663
Opened 2017-03-20 10:21 UTC by razu9861

2017-03-20 10:40 UTC, dogi requested changes

2017-03-20 10:40 UTC, dogi commented on init_docs/Text.json
> +  "Link_Copied":"Link copied to your clipboard",
`Link_Coppied` needs to be changed also in `app/nation/app/views/VipLinksView.js`

2017-03-20 10:43 UTC, razu9861 commented on init_docs/Text.json
> +  "Link_Copied":"Link copied to your clipboard",
sorry my bad, thanks for reminding me

2017-03-21 01:20 UTC, lmmrssa approved these changes

2017-03-21 01:20 UTC, lmmrssa commented on app/nation/app/Router.js
> +                        var listCommunity,div;
this var is not used anywhere and also it does not look right to have var with html tag name

2017-03-27 10:08 UTC, closed without merging