[#701]: Slider Added in Course-Step(connects #701)
open-learning-exchange/BeLL-Apps pull request #725
Opened 2017-04-04 09:56 UTC by Pr0chin

2017-04-06 06:25 UTC, dogi requested changes

2017-04-06 06:25 UTC, dogi commented on install_windows_community
> +#!/usr/bin/env node
as much as I like this script it has nothing to do with the slider ;)

@Pr0chin please remove this file from this PR

2017-04-06 06:46 UTC, Pr0chin commented on install_windows_community
> +#!/usr/bin/env node
ok sure @dogi  :D

2017-04-06 07:13 UTC, dogi approved these changes

2017-04-07 03:57 UTC, razu9861 approved these changes

2017-04-07 06:30 UTC, Rupesh87 approved these changes

2017-04-07 11:19 UTC, lmmrssa approved these changes

2017-04-10 09:52 UTC, closed without merging