650 course statistics(connects #650)
open-learning-exchange/BeLL-Apps pull request #743
Opened 2017-04-17 06:24 UTC by Pr0chin

2017-04-17 06:51 UTC, dogi requested changes

2017-04-17 06:51 UTC, dogi commented on app/MyApp/index.html
> +    <script src='app/views/CoursesStatistics.js'></script>
like in https://github.com/open-learning-exchange/BeLL-Apps/commit/bed65a653d15896e9eec9ebdbf3765e58fadbafa every javascript include in `index.html` needs a special comment

2017-04-17 07:08 UTC, Pr0chin commented on app/MyApp/index.html
> +    <script src='app/views/CoursesStatistics.js'></script>
ok gotch ya ;) :D

2017-04-17 09:08 UTC, dogi requested changes

2017-04-17 09:08 UTC, dogi commented on app/MyApp/index.html
> +    <script src='app/views/CoursesStatistics.js'></script> <!-- app/views.js -->
Good @Pr0chin ;)
but this is only half of the necessary changes
`app/views/CoursesStatistics.js` needs to be surrounded by double quotes `"`

2017-04-17 09:15 UTC, Pr0chin commented on app/MyApp/index.html
> +    <script src='app/views/CoursesStatistics.js'></script> <!-- app/views.js -->
okz ;) :D @dogi

2017-04-17 10:13 UTC, dogi approved these changes

2017-04-17 10:21 UTC, razu9861 approved these changes

2017-04-17 15:42 UTC, lmmrssa requested changes

2017-04-17 15:42 UTC, lmmrssa commented on app/MyApp/app/Router.js
> +            /*if (course.get('courseLeader').indexOf($.cookie('Member._id')) == -1  &&  roles.indexOf("Manager") == -1) {
not sure why this code is commented out so need some clarification

2017-04-17 15:42 UTC, lmmrssa commented on app/MyApp/app/collections/CourseAnswer.js
> +            if ( this.StepID != "" && this.QuestionID!= "" /*&& this.pqattempts == "undefined" && this.MemberID == "undefined"*/) {
need these commented out code from condition

2017-04-17 15:42 UTC, lmmrssa commented on init_docs/languages/English.txt
> +  "Errors": "Errors",
need to remove these new lines in English.txt only needed in Text.json

2017-04-18 04:55 UTC, Rupesh87 approved these changes

2017-04-18 09:19 UTC, Pr0chin commented on init_docs/languages/English.txt
> +  "Errors": "Errors",
removed from English.txt

2017-04-18 09:20 UTC, Pr0chin commented on app/MyApp/app/collections/CourseAnswer.js
> +            if ( this.StepID != "" && this.QuestionID!= "" /*&& this.pqattempts == "undefined" && this.MemberID == "undefined"*/) {
Did it :D

2017-04-18 09:20 UTC, Pr0chin commented on app/MyApp/app/Router.js
> +            /*if (course.get('courseLeader').indexOf($.cookie('Member._id')) == -1  &&  roles.indexOf("Manager") == -1) {
corrected

2017-04-19 00:10 UTC, dogi approved these changes

2017-04-24 07:48 UTC, dogi approved these changes

2017-04-27 04:24 UTC, closed without merging