[#747]: Hide download button as per required( connects #747)
open-learning-exchange/BeLL-Apps pull request #749
Opened 2017-04-19 06:27 UTC by Pr0chin

2017-04-20 04:36 UTC, Rupesh87 approved these changes

2017-04-20 04:48 UTC, razu9861 approved these changes

2017-04-20 08:40 UTC, lmmrssa requested changes

2017-04-20 08:40 UTC, lmmrssa commented on app/MyApp/index.html
> +                        <%if(attachmentName != null && attachmentName!= "") {%>
move tr inside the condition and remove else

2017-04-20 09:22 UTC, dogi approved these changes

2017-04-25 00:02 UTC, lmmrssa approved these changes

2017-04-27 04:26 UTC, closed without merging