[#750]:Last attempt text removed (connects #750)
open-learning-exchange/BeLL-Apps pull request #751
Opened 2017-04-19 11:31 UTC by razu9861

2017-04-20 01:19 UTC, dogi approved these changes

2017-04-20 04:34 UTC, Rupesh87 approved these changes

2017-04-20 04:37 UTC, Pr0chin approved these changes

2017-04-20 04:47 UTC, razu9861 commented
![screen shot 2017-04-20 at 10 29 50 am](https://cloud.githubusercontent.com/assets/24647983/25214036/a9053c34-25b4-11e7-9690-ea5687370e61.png)

2017-04-20 08:44 UTC, lmmrssa requested changes

2017-04-20 08:44 UTC, lmmrssa commented on app/MyApp/index.html
> +            <% if(questionlist == null){%>
'make the condition negative

2017-04-25 00:03 UTC, lmmrssa approved these changes

2017-04-27 04:27 UTC, closed without merging