[#755]-Save answer while finish button is pressed (connects #755)
open-learning-exchange/BeLL-Apps pull request #769
Opened 2017-04-24 08:52 UTC by razu9861

2017-04-24 10:04 UTC, leomaxi approved these changes

2017-04-24 10:45 UTC, dogi approved these changes

2017-04-25 05:11 UTC, Rupesh87 approved these changes

2017-04-25 07:00 UTC, Pr0chin approved these changes

2017-04-27 06:03 UTC, lmmrssa requested changes
How this feature is implemented will not do the expected job. It has flaw in it.

2017-04-27 07:29 UTC, dogi commented
@lmmrssa I am curious to see more about what you mean ;)

2017-05-03 10:03 UTC, closed without merging