[#725]:Fixed Badges Static Errors(connects #725)
open-learning-exchange/BeLL-Apps pull request #773
Opened 2017-04-25 06:25 UTC by Pr0chin

2017-04-25 06:39 UTC, Pr0chin commented
![badges](https://cloud.githubusercontent.com/assets/24644003/25371777/175e7f64-29b2-11e7-95a5-a2591403eb9d.PNG)

2017-04-25 08:09 UTC, dogi approved these changes

2017-04-25 08:10 UTC, dogi commented
@Pr0chin @razu9861 nice picture ;)

2017-04-27 05:22 UTC, lmmrssa requested changes

2017-04-27 05:22 UTC, lmmrssa commented on app/MyApp/index.html
> +            <%for (var i=1; i<status.length; i++) {%>
Status is for result 'Submitted/Unsubmitted' will be based upon does status for last attempt exist or not. If exist and status is -1 then also its unsubmitted

2017-05-01 08:37 UTC, lmmrssa approved these changes

2017-05-01 10:17 UTC, nirojdyola approved these changes

2017-05-02 03:46 UTC, dogi commented
@lmmrssa good catch ;)

2017-05-02 07:49 UTC, leomaxi approved these changes

2017-05-03 09:56 UTC, closed without merging