761 unaccepted community (connects #761)
open-learning-exchange/BeLL-Apps pull request #778
Opened 2017-05-01 08:29 UTC by razu9861

2017-05-01 09:42 UTC, Pr0chin requested changes

2017-05-01 09:42 UTC, Pr0chin commented on app/MyApp/app/views/ManageCommunity.js
> +            } else {}
else {} should be removed

2017-05-01 09:47 UTC, Pr0chin approved these changes

2017-05-02 03:44 UTC, dogi reviewed
@razu9861 awesome

2017-05-04 04:52 UTC, lmmrssa approved these changes

2017-05-04 04:52 UTC, lmmrssa commented on app/MyApp/app/views/Dashboard.js
> +                that.$el.html(_.template(this.template, this.vars));
fix indenting

2017-05-04 04:52 UTC, lmmrssa commented on app/MyApp/app/views/ManageCommunity.js
>              this.$el.append('<div style="padding: 20px 20px 0px 0px; float: left;"> <a id="publication" class="btn btn-primary" href="#publications/for-' + App.configuration.get('name') + '">' + App.
these also needs to be only when accepted

2017-05-04 04:52 UTC, lmmrssa commented on app/MyApp/app/Router.js
> +            var jsonModel = getRequestDocFromLocalDB();
where is this code used?

2017-05-05 05:40 UTC, closed without merging