[#761]:Lebel text replaced for Nation Reject/Pending(connects #761)
open-learning-exchange/BeLL-Apps pull request #789
Opened 2017-05-05 06:31 UTC by razu9861

2017-05-05 08:35 UTC, Rupesh87 approved these changes

2017-05-08 04:15 UTC, lmmrssa requested changes

2017-05-08 04:15 UTC, lmmrssa commented on app/MyApp/app/Router.js
> +                                                    $('#onlineButton').attr("title", App.languageDict.get("Nation_Pending"));
Need Nation invisible condition as well when not able to connect with nation

2017-05-08 04:15 UTC, lmmrssa commented on init_docs/Text.json
> +    "Nation_Rejected" : "Community registration request Pending"
Fix the translation

2017-05-08 18:31 UTC, dogi requested changes

2017-05-08 18:31 UTC, dogi commented on init_docs/Text.json
> +    "Nation_Rejected": "Community registration request Pending"
should this not be something other then `Nation_Rejected`
maybe `Nation_Pending` ?

2017-05-09 05:16 UTC, dogi approved these changes

2017-05-09 11:14 UTC, closed without merging