[#756]-Auto Review(connects #756)
open-learning-exchange/BeLL-Apps pull request #793
Opened 2017-05-08 09:56 UTC by razu9861

2017-05-08 18:35 UTC, dogi requested changes

2017-05-08 18:35 UTC, dogi commented on init_docs/Text.json
> +    "Test_Inprogress": "Test on progress"
`Test in progress` not `on`

2017-05-09 04:22 UTC, dogi approved these changes

2017-05-09 04:32 UTC, Pr0chin approved these changes

2017-05-09 04:45 UTC, lmmrssa approved these changes

2017-05-09 06:54 UTC, Rupesh87 approved these changes

2017-05-09 06:55 UTC, nirojdyola approved these changes

2017-05-09 11:12 UTC, closed without merging