[#629] Password Reset Issue Fixed (connects #629)
open-learning-exchange/BeLL-Apps pull request #794
Opened 2017-05-08 10:35 UTC by nirojdyola

2017-05-08 18:46 UTC, dogi requested changes
@nirojdyola think you should configure your editor so that tabs get converted to spaces ;)

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/Router.js
> +			mymail.fetch({
@nirojdyola looks like this are tabs ... please fix this whitespace issue ;)

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/models/Configuration.js
> +            kind: 'Text', // Saves kind of document according to corresponding db's.Mostly used in couch db views.
same whitespace issue here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/CommunityConfigurationsForm.js
> +			vars["passwordResetDuration"] = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];
and here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +				if(vars.type == "PasswordReset"){
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/CommunityConfigurationsForm.js
> +                Code: $.trim($('#community-code').val()),
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/CommunityConfigurationsForm.js
> +			$('#pwd_reset_duration').val(that.model.get('passwordResetDuration'));
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +				}
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +			var newCollection = new App.Collections.Mails({
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +			var modelNo = e.currentTarget.value;
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +			var senderId = model.get("senderId");
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MailView.js
> +			var senderId = model.get("senderId");
here

2017-05-08 18:46 UTC, dogi commented on init_docs/Text.json
> +    "Msg_Confirm_ResetPassword_ChangePassword": "You have recently updated password. Do you want to reset your password again ?If you click No then it will resend the password email again.",
and here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/index.html
> +				<div>
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +		updateLoggedInPasswordResetEmail: function(member){
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +					type : "PasswordReset"
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +							var subject;
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +			var self = this;
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +						var mail_dateTime;
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +							if(hr > duration && duration > 0){
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +								flag = "PasswordReset";
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +								flag = "Nothing";
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +		updatePasswordResetEmail: function(mailCollections){
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +			var self = this;
here

2017-05-08 18:46 UTC, dogi commented on app/MyApp/app/views/MemberLoginForm.js
> +										var mail = new App.Models.Mail();
here

2017-05-09 05:21 UTC, lmmrssa approved these changes

2017-05-09 05:26 UTC, dogi requested changes
sorry there are also trailing whitespaces

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +padding:5 5 0 5;
oops trailing spaces ;)

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +height:50px;
and here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +    text-align:left;
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +    padding: 16px 20px 15px 0px;
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> + border-top: 2px dashed #000000;
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +  overflow: hidden;
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Home.css
> +    margin-right: 5%;
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Router.js
> +                    $('#syncStatus').closest('div').hide();
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Router.js
> +                    $('#syncStatus').closest('div').hide();
oops my error ;) not here I mean

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Router.js
> +
here

2017-05-09 05:26 UTC, dogi commented on app/MyApp/app/Router.js
> +
here

2017-05-09 06:53 UTC, Rupesh87 approved these changes

2017-05-10 10:27 UTC, merged