[#736] Auto Accepted Community Feature (connects #736)
open-learning-exchange/BeLL-Apps pull request #808
Opened 2017-05-15 09:16 UTC by nirojdyola

2017-05-16 04:46 UTC, dogi requested changes
@nirojdyola if I understand you are autoaccepting every community every time ...

maybe I am wrong ;)
the issue addresses something different

like we add something to configuration doc so that this autoaccepting will happen

2017-05-22 08:02 UTC, nirojdyola commented
While deleting a document of  one environment from another environmnet,  I got the problem CORS. Then, I changed the CORS config in the couch db configurations :
In the cors section I have added 
headers : accept, authorization, content-type, origin, referer, cache-control, x-requested-with
methods: GET, PUT, POST, HEAD, DELETE
origins	: *
I have changed in the environment http://ht.np.ole.org:5982 .

2017-05-22 08:05 UTC, nirojdyola commented
![autoaccept](https://cloud.githubusercontent.com/assets/7495421/26298081/8a942af8-3ef5-11e7-98b0-c0dde130caed.png)

2017-05-26 05:15 UTC, Pr0chin approved these changes

2017-05-26 05:16 UTC, Rupesh87 approved these changes

2017-06-01 06:31 UTC, lmmrssa approved these changes

2017-06-06 03:54 UTC, closed without merging