[#820]: FIX COURSE ERROR (connects #820)
open-learning-exchange/BeLL-Apps pull request #821
Opened 2017-05-19 09:15 UTC by Pr0chin

2017-05-22 08:40 UTC, dogi approved these changes

2017-05-22 10:05 UTC, Rupesh87 approved these changes

2017-05-22 11:37 UTC, razu9861 commented
@Pr0chin are those console necessary

2017-05-22 11:51 UTC, razu9861 commented
@Pr0chin are those console necessary

2017-05-23 05:05 UTC, lmmrssa requested changes

2017-05-23 05:05 UTC, lmmrssa commented on app/MyApp/app/views/CourseLevelsTable.js
> +                console.log(sr[index][totalattempt[index]],(sr[index] instanceof Array))
can be removed

2017-05-23 05:05 UTC, lmmrssa commented on app/MyApp/app/views/CourseStepStatistics.js
> +                console.log(questionlist.attributes.stepType)
can be removed

2017-05-23 05:05 UTC, lmmrssa commented on app/MyApp/app/views/takeTestView.js
> +                console.log(sstatus[this.stepindex][pqattemptss[this.stepindex]])
can be removed

2017-05-23 05:05 UTC, lmmrssa commented on app/MyApp/index.html
> +                    <% for(var j = 0; j < steps.length; j++) {%>
not sure how it looks with the loop

2017-05-25 04:28 UTC, lmmrssa approved these changes

2017-05-30 02:22 UTC, closed without merging