[#831]: Changed My Tutor to My Team(connects #831)
open-learning-exchange/BeLL-Apps pull request #835
Opened 2017-05-29 04:49 UTC by Pr0chin

2017-05-30 20:42 UTC, dogi requested changes
@Pr0chin `Teams` not Team ;)

2017-05-30 20:42 UTC, dogi commented on init_docs/Text.json
> +    "My_Team": "My Team",
please use plural

2017-05-30 20:42 UTC, dogi commented on app/MyApp/app/Router.js
> +            wordsOfLibraryTable.push(App.languageDict.attributes.My_Team);
please use plural

2017-06-01 06:19 UTC, Pr0chin commented on app/MyApp/app/Router.js
> +            wordsOfLibraryTable.push(App.languageDict.attributes.My_Team);
sure @dogi  👍 :D

2017-06-01 15:10 UTC, lmmrssa approved these changes

2017-06-02 14:28 UTC, leomaxi approved these changes

2017-06-06 03:53 UTC, closed without merging