[#915]-community list search fixed (connects #915)
open-learning-exchange/BeLL-Apps pull request #919
Opened 2017-07-03 04:11 UTC by Rupesh87

2017-07-03 05:06 UTC, Pr0chin approved these changes

2017-07-03 05:29 UTC, lmmrssa requested changes
jsonModels1 is not used anymore. It gets list from two different table so instead of using just one table it will be better if we can check if region already exist before adding from another table.

2017-07-03 08:25 UTC, nirojdyola approved these changes

2017-07-04 04:13 UTC, Pr0chin approved these changes

2017-07-05 10:51 UTC, lmmrssa commented
there might be some region missing between table so need to include both tables but make it unique by checking does it already exist or not.

2017-08-01 09:38 UTC, closed without merging