[#991] CourseAddRes undefined resources sorted (connects #911)
open-learning-exchange/BeLL-Apps pull request #992
Opened 2017-08-15 06:55 UTC by razu9861

2017-08-15 09:06 UTC, Pr0chin approved these changes

2017-08-15 09:07 UTC, nirojdyola approved these changes

2017-08-15 09:09 UTC, Rupesh87 approved these changes

2017-08-17 11:52 UTC, dogi requested changes

2017-08-17 11:52 UTC, dogi commented on app/MyApp/app/views/LevelDetail.js
> +                alert(App.languageDict.attributes.Prompt_Reource_first)
Reource?

2017-08-21 06:45 UTC, razu9861 commented on app/MyApp/app/views/LevelDetail.js
> +                alert(App.languageDict.attributes.Prompt_Reource_first)
it means
Prompt_Reource_first = Please select resource first

2017-08-24 05:06 UTC, lmmrssa commented on app/MyApp/app/views/LevelDetail.js
> +                alert(App.languageDict.attributes.Prompt_Reource_first)
@razu9861  please change the attribute and wherever its previously used

2017-09-12 10:49 UTC, dogi approved these changes

2017-09-12 10:55 UTC, merged